Prest Workspace & Menu
======================

Workspace area
--------------

Prest's **workspace** is the area where all datasets (either imported from file or generated by the user through Prest) 
are available for analysis and/or export.

The three columns in the workspace area provide the following information about the datasets listed there:

   * **Name**: the name of the dataset, as imported from file or specified by the user through a Prest operation.
   
   * **Alternatives/Goods**: depending on whether the dataset in question is :ref:`general <general-datasets>` or :ref:`budgetary <budgetary-datasets>`, the total number of alternatives or goods in that dataset is shown, respectively.
   
   * **Size**: the total number of subjects and observations in the dataset.
   
Right-clicking on a dataset in the workspace area leads to the following options:
 
 
   * **View**: displays the contents of the dataset in a separate window (this is also done by double-clicking on the dataset).
   
   * **Analysis**: the available options here depend on whether the selected dataset is :ref:`general <general-datasets>` or :ref:`budgetary <budgetary-datasets>`:
      
     * **General datasets**

              * **Integrity check**: This option checks if: 

                     (a) the specified choices in the dataset are indeed elements of the corresponding menus of alternatives; 

                     (b) any menus are repeated more than once for a given subject in the dataset.

              A detailed report/dataset is produced if one of the above is true.

              * **Summary information**: This option generates a new dataset that gives the following counts per subject: 

                     1) *Observations*.

                     2) *Active choices* (number of times where the outside option -if feasible-  was *not* chosen).

                     3) *Deferrals* (number of times where the outside option *was* chosen).

               The dataset that results from this operation is named after the original dataset following insertion of the "(info)" suffix. For example, applying this operation on *"DatasetX"* generates *"DatasetX (info)"*, while the original dataset *"DatasetX"* is also kept in the workspace.
			   
              * **Consistency analysis**: details :ref:`here <general-consistency-tip>`. 

              * **Inconsistent tuples of menus**: details :ref:`here <menu-tuples>`. 
		
              * **Inconsistent tuples of alternatives**: details :ref:`here <alternative-tuples>`.

              * **Model estimation**: details :ref:`here <estimation>`.

              * **Merge choices at the same menu**: details :ref:`here <merging-tip>`.  

              * **Generate similar random dataset**: details :ref:`here <similar-random-dataset>`.
              	 
					 
     * **Budgetary datasets** 

              * **Consistency analysis**: details :ref:`here <budgetary-consistency-tip>`.

   
   * **Export**: this allows for exporting the selected dataset in .xlsx or .csv format. 

     Special remarks for this option:

     * Dataset derived from **Model estimation** (more details :ref:`here <estimation>`):

         1) **Compact (human-friendly)**: leaves the subject column blank in all but the first row whenever there are multiple compatible models for a given subject.
		 
         2) **Detailed (machine-friendly)**: includes subject information in every row.

   
     * Dataset derived from **Consistency analysis** (more details :ref:`here <general-consistency-tip>`):

         * **Summary**
		  
         * **WARP violations**
		  
         * **Congruence violations (wide)**
		   
         * **Strict general cycles (wide)**
		   
         * **Strict binary cycles (wide)**
		   
         * **Binary cycles (wide)**
		   
   * **Delete**: removes the selected dataset from the workspace area.


Drop-down menu options
----------------------

  * **Workspace**:

      * **Clear**: clears all datasets from the workspace area.
	  
      * **Restore from file**: opens an existing Prest workspace file (.pwf) from the relevant directory.
	  
      * **Save**: saves the active Prest workspace file in the current location.
	  
      * **Save as**: allows to choose the location where the active Prest workspace file will be saved.
	  
      * **Import general dataset**: details :ref:`here <general-datasets>`.
	  
      * **Import budgetary dataset**: details :ref:`here <budgetary-datasets>`.
	  
      * **Quit**: exits the application.

  * **Simulation**: details :ref:`here <direct-simulations>`.
  
  * **Help**:

      * **Prest manual**: opens the embedded documentation page on the user's web browser.

      * **About**: opens a dialog with information about Prest's version, copyright and license. 	  