language: generic
os: osx
osx_image: xcode11.3

before_install:
  - cd prest-build
  - bash setup-for-mac.sh

install:
  - bash build-mac.sh

before_script:
  - cd ..
  - export PATH="$HOME/.cargo/bin:$HOME/Library/Python/3.7/bin:$PATH"

script:
  - make fulltest
