#!/usr/bin/env python3
#
# Prest documentation build configuration file
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('extensions'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '8.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.todo',
  # 'sphinx.ext.imgmath',  ## TODO: enable this for production
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinxcontrib.bibtex',
    'sphinx.ext.autosectionlabel',
    'sphinx-mathjax-offline',
    'sphinxcontrib.googleanalytics'
]

googleanalytics_id = 'G-6Q5ER87GKE'

#bibtex_bibliography_header = ".. rubric:: References"
#bibtex_footbibliography_header = ""
bibtex_bibfiles = ['references_theory.bib','references_psych.bib','references_comp.bib']

bibtex_encoding = 'utf-8-sig'
# bibtex_default_style = 'plain'
# bibtex_default_style = 'unsrt'

#mathjax_path = 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'
#mathjax_path = 'https://prestsoftware.com/_static/mathjax/MathJax.js?config=TeX-MML-AM_CHTML'
#mathjax_path = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js'

# For DOI external links

extlinks = {
    'doi': ('https://dx.doi.org/%s', 'doi:'),
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Prest'
copyright = '2018-2025, Georgios Gerasimou, Matúš Tejiščák'
author = 'Georgios Gerasimou, Matúš Tejiščák'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
try:
    with open('../doc-version.txt') as f:
        version = f.read().strip()
except OSError:
#    version = '(no version)'
    version = ''
# The full version, including alpha/beta/rc tags.
release = version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

html_theme = 'sphinx_material'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.

html_theme_options = {

    # Set the name of the project to appear in the navigation.
    'nav_title': 'Prest',

    # Set you GA account ID to enable tracking
    'google_analytics_account': '125271613',

    # Specify a base_url used to generate sitemap.xml. If not
    # specified, then no sitemap will be built.
    'base_url': 'https://prestsoftware.com',

    # Set the color and the accent color
    'color_primary': 'blue',
    'color_accent': 'light-blue',

    # Set the repo location to get a badge with stats
    'repo_url': 'https://github.com/prestsoftware/prest',
    'repo_name': 'Prest',

    # Visible levels of the global TOC; -1 means unlimited
    'globaltoc_depth': 3,
    # If False, expand all TOC entries
    'globaltoc_collapse': True,
    # If True, show hidden TOC entries
    'globaltoc_includehidden': False,

    # 'html_minify': True,
    # 'css_minify': True,
}

# Hide source code link
html_show_sourcelink = False

html_sidebars = {
    "**": ["globaltoc.html"]
}

# Suppress config.cache warning
suppress_warnings = ["config.cache"]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_favicon = '_static/favicon.png'
# html_css_files = ['my_theme.css']


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'Prestdoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'Prest.tex', 'Prest Documentation',
     'Georgios Gerasimou, Matúš Tejiščák', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'Prest', 'Prest Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'Prest', 'Prest Documentation',
     author, 'Prest' 'Georgios Gerasimou', 'Matúš Tejiščák'),
]

default_role = 'math'
imgmath_image_format = 'svg'
imgmath_latex_preamble = r'''
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{amsopn}
\usepackage{amsthm}
\usepackage{latexsym}
\usepackage{setspace}
\usepackage{color}
\usepackage{microtype}
\usepackage[bookmarks=true,
bookmarksnumbered=true,
pdfpagemode=None,pdfstartview=FitH,
hidelinks]{hyperref}

\newcommand{\R}{\mathbb{R}}

\parindent=0pt
\parskip=0pt
'''

language = 'en'
